version: '3.8'

networks:
  kong-net:
    driver: bridge

services:
  kong:
    image: kong/kong-gateway:3.8.0.0
    volumes:
      # Mount the Mirror Inject configuration file
      - ./conf/templates/mirror-inject.conf:/usr/local/kong/mirror-inject.conf
      # Mount the Data Plane Certificates
      - .tls:/usr/local/ssl
      - ./kong.yaml:/kong.yaml
    environment:
      #####################################################################
      # Start: Additonal Kong environment variables for Mirroring Requests
      #####################################################################
      KONG_NGINX_PROXY_INCLUDE: mirror-inject.conf
      KONG_NGINX_LOCATION_MIRROR: /mirror
      KONG_NGINX_LOCATION_MIRROR_REQUEST_BODY: on
      #####################################################################
      # End: Additonal Kong environment variables for Mirroring Requests
      #####################################################################
      KONG_DATABASE: off
      KONG_VITALS: off
      KONG_LUA_SSL_TRUSTED_CERTIFICATE: system
      KONG_DECLARATIVE_CONFIG: kong.yaml

    ports:
      - "8000:8000"
      - "8443:8443"
    networks:
      - kong-net
  
  echo:
    image: mendhak/http-https-echo:35
    ports:
      - "8080:8080"
      - "8445:8443"
    networks:
      - kong-net